apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-backend-cluster
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: ClientID
          name: azure-secret-sp
          namespace: default
        clientSecret:
          key: ClientSecret
          name: azure-secret-sp
          namespace: default
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: ce7d5417-3fd8-4d3c-b82f-1f62f56f5acb
      vaultUrl: https://no-weu-tst-shared-kv.vault.azure.net